package com.sunsetrebel.catsy.enums;

public enum EventThemes {
    SPORT, MUSIC, ART, QUEST, HOOKAH, SHOPPING, FILM, BIRTHDAY, WALKING, JOB, JOGGING,
    WORKOUT, TATTOO, HEALTH, PETS, FISHING, CARS, TRAVEL, EXCURSION, GAMES, ALCOHOL,
    ROCKNROLL, EXHIBITION, FAIR, COMEDY, PARTY, ROMANCE, KIDS, FASHION, PHOTO, TECHNOLOGY,
    ANIME, RELIGION, DANCE, LGBTQ, STUDY, BOOKS
}
